### ISSUE TITLE
Autonomous control help

### ISSUE THREAD

**Issue by DevJav** [lnotspotl/notspot_sim_cpp#1]
Hi!

We're trying to make an automated control for your robot, but we are having trouble because we need some kind of odometry and a /cmd_vel topic to command the movement to the robot.

We don't know how to do this so if you can help us with some information we would be grateful.

Thanks!

**Comment by lnotspotl** [comment]
Hi,

in [RobotController.cpp](https://github.com/lnotspotl/notspot_sim_cpp/blob/main/src/notspot_controller/src/RobotController/RobotController.cpp), there is a callback function __joystick_command__, which receives messages from the __notspot_joy/joy_ramped__ topic and distributes these messages to other controllers, which use them to adjust their parameters. The __TrotGaitController__ uses the data in the message to set the desired walking velocity. The main goal of this project was namely for the robot to be controllable using a joystick.

If you want to control the walking velocity over a different topic, let's say __/cmd_vel__, you can add a new callback function, which only communicates with the __TrotGaitController__ and sets the desired velocity. You can afterwards publish your desired velocity on this topic and when the current controller is set to __TrotGaitController__, the velocity would be adjusted.

I hope this helps a bit, feel free to ask some further questions in case something is still unclear.

Thanks
