### ISSUE TITLE
Not able to use trot gate controller with Xbox one joystick

### ISSUE THREAD

**Issue by shivam15sharmaulp** [lnotspotl/notspot_sim_cpp#3]
I have tried all the buttons X, Y, A, and B and none of the buttons turn on the trot gate. Is there a way to make use of the trot gate controller using the Xbox One joystick?

**Comment by lnotspotl** [comment]
Hi.

I wrote the software a couple of years ago when I was still a bit inexperienced. I still am, but hopefully less so.

This [link](https://github.com/lnotspotl/notspot_sim_cpp/blob/9716cef5d03eb52e00b447e5a3fa501aaee5e148/src/notspot_controller/src/RobotController/RobotController.cpp#L87) will lead you to the very function that is meant to switch between controllers. 
Can you turn your joystick node on and check which button flags get activated when you press the physical buttons? This should allow you to modify the source code and get the software going.

Let me know how it went.
